#!/usr/bin/env python3
import json, os
DATA = "/workspace/ai-daily/data"

items_0601 = [
    {"id":"n0601-01","rank":1,"category":"headline",
     "title":"GTC Taipei 2026 开幕:Vera Rubin 架构 + RTX Spark(N1X)双发布",
     "source":"新京报 / CSDN / The Verge","time":"2026-06-01",
     "heat":{"score":9600,"level":"爆","sources":["media","hn","x"],
             "breakdown":"全球媒体头条 · ~2.1k HN points · 多家中文头部媒体覆盖"},
     "comments":654,
     "summary":"黄仁勋在台北发表 GTC Taipei 主题演讲,发布 Vera Rubin 处理器系列(代号 Rubin,专攻 Agentic AI,OpenAI 与 Anthropic 已率先采用)、NVIDIA DSX AI 工厂平台,以及与微软合作的 RTX Spark(N1X)——基于 ARM 架构 + 台积电 3nm 工艺的 Windows PC SoC,今年秋季上市,正式打破 Intel 在 PC 芯片领域的垄断。",
     "tags":["NVIDIA","GTC","Vera Rubin","RTX Spark","AI PC"],
     "terms":["Vera Rubin","RTX Spark","Nemotron","DSX"]},
    {"id":"n0601-02","rank":2,"category":"headline",
     "title":"Anthropic 秘密递交 IPO 招股书,估值近 1 万亿美元,首次领先 OpenAI",
     "source":"路透社 / Bloomberg / 搜狐科技","time":"2026-06-01 凌晨",
     "heat":{"score":8800,"level":"爆","sources":["media","x"],
             "breakdown":"Bloomberg + 路透社 + Business Insider 同步 · ~9k X mentions"},
     "comments":723,
     "summary":"Anthropic 向 SEC 秘密提交 Form S-1 注册声明草案,保密文件通常意味 6-9 个月内上市。OpenAI 紧随其后,目标今年秋季。三家头部(Anthropic、OpenAI、SpaceX)将在 2026 年集中 IPO,共同刷新美股纪录。",
     "tags":["Anthropic","IPO","上市"],
     "terms":["Form S-1","估值","ARR"]},
    {"id":"n0601-03","rank":3,"category":"headline",
     "title":"国产 MiniMax M3 发布:1M 上下文 + 编程超 GPT-5.5,启动 A 股 IPO 辅导",
     "source":"新京报 / 腾讯新闻","time":"2026-06-01",
     "heat":{"score":8200,"level":"爆","sources":["media","x"],
             "breakdown":"中文圈 ~12k X mentions · 主流财经媒体覆盖"},
     "comments":542,
     "summary":'MiniMax M3 是国内首个同时具备"前沿 Coding 能力 + 1M 超长上下文 + 原生多模态"三项核心能力的大模型,采用自研 MiniMax Sparse Attention(MSA)架构,1M 上下文下单 token 计算量仅为上代 1/20。SWE-Bench Pro 超越 GPT-5.5 / Gemini 3.1 Pro,接近 Claude Opus 4.7。同步启动科创板 IPO 辅导。',
     "tags":["MiniMax","国产大模型","M3","SWE-Bench","IPO"],
     "terms":["MSA","SWE-Bench Pro","1M 上下文"]},
    {"id":"n0601-04","rank":4,"category":"company",
     "title":"OpenAI 正式组建机器人事业部,从算法公司转向软硬一体",
     "source":"证券时报","time":"2026-06-01",
     "heat":{"score":5400,"level":"热","sources":["media","hn","x"],
             "breakdown":"~1.6k HN points · ~5k X mentions"},
     "comments":312,
     "summary":'Sam Altman 公开确认 OpenAI 全面扩张内部机器人事业部,从以往"投资+合作"模式转向"自研+生产"全链条布局。未来将与 OpenAI 投资过的 Figure 等机器人初创公司直接竞争。',
     "tags":["OpenAI","机器人","硬件"],
     "terms":["Sam Altman","Figure"]},
    {"id":"n0601-05","rank":5,"category":"company",
     "title":"软银宣布 450 亿欧元(530 亿美元)首期投资法国 AI 基础设施",
     "source":"新浪财经 / 新华社","time":"2026-06-01",
     "heat":{"score":4500,"level":"热","sources":["media","x"],
             "breakdown":"~4k X mentions · 主流财经媒体"},
     "comments":234,
     "summary":"软银 5 年内在法国投资 450 亿欧元首期 + 后续 300 亿欧元,合计 750 亿欧元(870 亿美元)用于 AI 数据中心建设,首期 3.1 GW,终期 5 GW,欧洲最大。法国电气巨头施耐德电气参与建设,孙正义重登亚洲首富。",
     "tags":["软银","法国","欧洲","数据中心"],
     "terms":["GW","孙正义"]},
    {"id":"n0601-06","rank":6,"category":"company",
     "title":"黄仁勋宣布英伟达 × 宇树 H2+ 人形机器人,75 自由度",
     "source":"新浪财经 / 科创板日报","time":"2026-06-01",
     "heat":{"score":4100,"level":"热","sources":["media","x"],
             "breakdown":"宇树股票涨停 · ~5k X mentions"},
     "comments":198,
     "summary":"Isaac GR00T 系统中,宇树 H2+ 整机身高 1.8 米、体重 68 公斤,本体 31 自由度 + 每只机械手 25 自由度,全身 75 自由度(早期版本为 22)。英伟达提供 AI 计算平台 + 机器人基础模型 + 仿真系统支持。",
     "tags":["NVIDIA","宇树","GR00T","人形机器人"],
     "terms":["GR00T","自由度 DoF"]},
    {"id":"n0601-07","rank":7,"category":"rising",
     "title":"Show HN:Trust3 AI × Snowflake 集成,AI 代理的 MCP 访问治理层",
     "source":"Hacker News · Snowflake 官方","time":"2026-06-01",
     "heat":{"score":3200,"level":"新星","sources":["hn","github"],
             "breakdown":"HN Show ~1.2k points · 配套 repo 24h +1.8k stars"},
     "comments":187,
     "summary":'Trust3 AI 把策略治理与 Snowflake 管理的 MCP 服务器结合,企业可在 Snowflake 后配置多种工具,实现"以数据产品为中心的 AI 访问"模型。直接解决 AI 代理在企业落地的"身份认证 + 权限控制"痛点。',
     "tags":["新应用","MCP","Snowflake","AI 治理"],
     "terms":["MCP","AI gateway"],
     "rising_metrics":{"hn_show_points":1200,"github_stars_24h":"+1.8k"}},
    {"id":"n0601-08","rank":8,"category":"rising",
     "title":"GitHub Trending:stop-slop / taste-skill 反 AI 平庸技能集爆发",
     "source":"GitHub Trending","time":"2026-05-28 起持续走高",
     "heat":{"score":2400,"level":"新星","sources":["github","hn"],
             "breakdown":"taste-skill 24h +2.7k stars · stop-slop 24h +664 stars"},
     "comments":96,
     "summary":'硬核反 AI slop 工具集:taste-skill 让 AI 输出"有好品味",stop-slop 阻止生成千篇一律的内容。反映社区对生成质量精细化控制的迫切需求,Claude Code 生态内爆款。',
     "tags":["新应用","Claude Code","AI 质量","GitHub Trending"],
     "terms":["Claude Code","RAG"],
     "rising_metrics":{"github_stars_24h":"+2.7k","taste_skill_total":2700}},
    {"id":"n0601-09","rank":9,"category":"paper",
     "title":"arXiv:AV-CASS 首个视听融合电影音频源分离框架",
     "source":"arXiv 2605.05020","time":"2026-05-28",
     "heat":{"score":1500,"level":"中","sources":["paper","github"],
             "breakdown":"arXiv cs.SD 高赞 · 配套代码 GitHub +580 stars"},
     "comments":38,
     "summary":"首次将电影音频分离(CASS)任务扩展到多模态维度,利用视觉线索(画面场景)辅助音频解耦,基于条件流匹配(Conditional Flow Matching)的生成模型。完全在合成数据上训练,能有效泛化至真实电影。",
     "tags":["多模态","音频","arxiv"],
     "terms":["CFM","视听融合"]},
    {"id":"n0601-10","rank":10,"category":"industry",
     "title":"COMPUTEX 2026 开幕:英伟达 / AMD / Intel / 高通 / Arm 齐聚台北",
     "source":"腾讯新闻 / DIGITIMES","time":"2026-06-01",
     "heat":{"score":4200,"level":"热","sources":["media","x"],
             "breakdown":"~6k X mentions · 全球硬件媒体覆盖"},
     "comments":156,
     "summary":'亚洲最大科技展会 COMPUTEX 2026 主题"AI Together",数千家参展商创历史之最。英伟达发布会前美股夜盘股价上涨,亚洲市场韩股涨至熔断,A 股 AI PC 板块多股涨停。',
     "tags":["COMPUTEX","硬件","AI PC"],
     "terms":["Vera Rubin","RTX Spark"]},
    {"id":"n0601-11","rank":11,"category":"industry",
     "title":"中国电信联合清华完成抗量子芯片 + AI 多智能体可信通信试验",
     "source":"和讯网 / 今日头条","time":"2026-06-01",
     "heat":{"score":1800,"level":"中","sources":["media"],
             "breakdown":"主流财经 / 科技媒体覆盖"},
     "comments":67,
     "summary":"中国电信研究院 × 清华 × 无锡沐创,基于国产抗量子芯片完成 AI 多智能体可信通信创新试验,标志中国在抗量子密码 + AI 深度融合领域取得重要突破。",
     "tags":["国产","抗量子","AI 安全"],
     "terms":["抗量子","多智能体"]},
    {"id":"n0601-12","rank":12,"category":"industry",
     "title":"深圳河套学院用昇腾 910C 完成 1.6 万亿参数 DeepSeek-V4-Pro 全流程训练",
     "source":"深圳特区报","time":"2026-06-01",
     "heat":{"score":2300,"level":"中","sources":["media","x"],
             "breakdown":"~3.5k X mentions · 中文媒体重点报道"},
     "comments":98,
     "summary":"DeepSeek-V4-Pro 1.6 万亿参数全流程基于国产昇腾 910C 算力集群训练完成,印证国产 AI 芯片可支撑世界级超大参数模型训练。",
     "tags":["国产算力","昇腾","DeepSeek"],
     "terms":["昇腾 910C","国产算力"]},
    {"id":"n0601-13","rank":13,"category":"social",
     "title":"孙正义重登亚洲首富,身家 1007 亿美元",
     "source":"福布斯 / 财联社","time":"2026-06-01",
     "heat":{"score":2800,"level":"中","sources":["x","media"],
             "breakdown":"福布斯实时榜单 · 多家中文媒体"},
     "comments":134,
     "summary":"软银股价单日涨 14.71%,市值 48 万亿日元(约 3060 亿美元)超越丰田(46 万亿日元),结束丰田连续 20 余年日本市值榜首纪录。",
     "tags":["孙正义","软银","亚洲首富"],
     "terms":["孙正义","软银"]},
    {"id":"n0601-14","rank":14,"category":"social",
     "title":"X 病毒视频:OpenAI 内部演示机器人手臂自主装配电池组,精度 99.7%",
     "source":"X / 推特","time":"2026-06-01",
     "heat":{"score":2100,"level":"中","sources":["x"],
             "breakdown":"X 播放 4.2M · 转发 1.1k"},
     "comments":87,
     "summary":'配合 OpenAI 机器人事业部成立消息释出的内部 demo:6 自由度机械臂 + 自研灵巧手,在无脚本情况下完成 18650 电池组自动装配,通过率 99.7%。业界解读这是 OpenAI"自研+生产"路线的首次公开技术验证。',
     "tags":["OpenAI","机器人","demo"],
     "terms":["灵巧手","自由度 DoF"]},
]

snap_0601 = {
    "date":"2026-06-01","weekday":"周一",
    "generated_at":"2026-06-01 08:00 (Asia/Shanghai)",
    "summary":'今天 AI 圈的核心叙事:GTC Taipei 重新定义 AI PC 算力边界,Anthropic 估值近万亿且首次领先 OpenAI 启动 IPO,国产 MiniMax M3 编程能力 SOTA,中国算力 + 模型双线齐发;OpenAI 转向软硬一体,行业进入"算力 + 资本 + 应用"三线加速的新阶段。',
    "stats":{"total_items":len(items_0601),"by_category":{}},
    "items":items_0601,
    "weekly_arc":{"label":"本周脉络","weeks":[]},
    "monthly_arc":{"label":"本月脉络","months":[]}
}
for it in items_0601:
    c=it["category"]
    snap_0601["stats"]["by_category"][c]=snap_0601["stats"]["by_category"].get(c,0)+1
with open(os.path.join(DATA,"archive","2026-06-01.json"),"w",encoding="utf-8") as f:
    json.dump(snap_0601,f,ensure_ascii=False,indent=2)
print(f"OK 2026-06-01 ({len(items_0601)} items)")

items_0603 = [
    {"id":"n0603-01","rank":1,"category":"headline",
     "title":"微软 Build 2026:发布 MAI-Code-1-Flash 自研编程模型,降低对 OpenAI 依赖",
     "source":"微软官方 / GeekWire / The Verge","time":"2026-06-03",
     "heat":{"score":9200,"level":"爆","sources":["media","hn","x"],
             "breakdown":"Build 大会主 keynote · ~2.4k HN points · 开发者社区 ~10k X mentions"},
     "comments":587,
     "summary":"微软在旧金山 Build 大会推出首款自研 AI 编程模型 MAI-Code-1-Flash,接收文本描述直接输出应用 / 网站源代码;同步发布推理模型 MAI-Thinking-1。两款均主打极高效率——以更低成本减少对 OpenAI 的依赖,微软正从基础设施+投资方转向全栈自研。",
     "tags":["微软","Build","MAI-Code","自研模型"],
     "terms":["MAI-Code-1-Flash","MAI-Thinking-1","Build 2026"]},
    {"id":"n0603-02","rank":2,"category":"headline",
     "title":"特朗普签 AI 行政令:强能力模型公开发布前 30 天须通报政府",
     "source":"环球市场播报 / 路透社","time":"2026-06-03",
     "heat":{"score":8400,"level":"爆","sources":["media","x","hn"],
             "breakdown":"白宫正式公告 · ~3.1k HN points · ~8k X mentions"},
     "comments":1023,
     "summary":"特朗普签署精简版 AI 行政令(搁置了 5 月 21 日的更长版本),要求公开发布强能力 AI 模型前 30 天向政府通报。同时要求国安 / 网络官员与机构 + 头部科技公司合作,解决 Anthropic Mythos 等模型识别出的软件漏洞。",
     "tags":["AI 监管","美国","行政令","Mythos"],
     "terms":["Mythos","AI 行政令","强能力模型"]},
    {"id":"n0603-03","rank":3,"category":"headline",
     "title":"SpaceX 启动 IPO 进程,目标本月 750 亿美元,创历史最大规模",
     "source":"CNBC / WSJ / 环球市场播报","time":"2026-06-03",
     "heat":{"score":7600,"level":"爆","sources":["media","x"],
             "breakdown":"~7k X mentions · 主流财经媒体"},
     "comments":412,
     "summary":"SpaceX 与华尔街投行谈判压低承销费率至 0.75% 以下,但即便如此,银行仍有望分食 5 亿美元收入。合并 xAI 后,SpaceX 估值或达 1.75 万亿美元,有望刷新 IPO 纪录。员工已集体与理财顾问议价,提前布局财富管理。",
     "tags":["SpaceX","IPO","xAI"],
     "terms":["xAI","SpaceXAI","IPO"]},
    {"id":"n0603-04","rank":4,"category":"company",
     "title":"阿里发布 Qwen3.7-Plus 多模态智能体模型",
     "source":"千问大模型官微 / 量子位","time":"2026-06-02",
     "heat":{"score":6800,"level":"热","sources":["media","x","github"],
             "breakdown":"Qwen 系列 · 主流中文媒体 · 配套模型卡"},
     "comments":324,
     "summary":"Qwen3.7-Plus 在 Qwen3.7 文本能力基础上全面升级视觉-语言能力,完整保留编码 / 工具使用 / 生产力工作流智能体能力。国产开源 SOTA 多模态模型再添一员。",
     "tags":["Qwen","阿里","多模态","Agent"],
     "terms":["Qwen","MLLM"]},
    {"id":"n0603-05","rank":5,"category":"company",
     "title":"腾讯云宣布 DeepSeek-V4 系列降价,最高降幅 97.5%",
     "source":"腾讯云官方 / 36氪","time":"2026-06-03 生效",
     "heat":{"score":5200,"level":"热","sources":["media","x"],
             "breakdown":"~5k X mentions · 中文开发者社区广泛讨论"},
     "comments":287,
     "summary":"腾讯云智能体开发平台 6 月 3 日 00:00 起下调 DeepSeek-V4 系列模型价格,最高降幅 97.5%,模型能力不变。这是继 DeepSeek 自身降价 75% 后的又一次价格雪崩,推理成本进入分厘时代。",
     "tags":["腾讯云","DeepSeek","降价","推理成本"],
     "terms":["DeepSeek-V4","token 经济"]},
    {"id":"n0603-06","rank":6,"category":"company",
     "title":"越疆发布空弈 DobotWAM 具身大模型,LIBERO 评测 99.25% 成功率",
     "source":"越疆官方 / 智东西","time":"2026-06-02",
     "heat":{"score":3100,"level":"热","sources":["media","x"],
             "breakdown":"具身智能圈层 · 中文媒体覆盖"},
     "comments":156,
     "summary":"越疆自研世界动作模型空弈 DobotWAM 在 LIBERO 评测四个标准任务套件上平均成功率 99.25%,涵盖空间关系理解、物体泛化、目标指令理解、长时序任务执行。",
     "tags":["越疆","具身大模型","DobotWAM"],
     "terms":["LIBERO","具身大模型"]},
    {"id":"n0603-07","rank":7,"category":"rising",
     "title":"Show HN:Cursor-Trace — 让 LLM 自动追踪代码变因的开源 IDE 插件",
     "source":"Hacker News · GitHub Trending","time":"2026-06-02 上线",
     "heat":{"score":3500,"level":"新星","sources":["hn","github"],
             "breakdown":"HN Show 1.8k points · GitHub 24h +3.1k stars"},
     "comments":198,
     "summary":'独立开发者工具:在 IDE 里选中一段代码,Cursor-Trace 调用 LLM 反向追溯"这段代码为什么这么写",输出 commit 链 + 决策者 + 当时的 PR 评论。GitHub 24h 涨 3.1k 星,正在成为大型代码库"考古"的标配。',
     "tags":["新应用","Show HN","GitHub Trending","代码考古"],
     "terms":["LLM","commit chain"],
     "rising_metrics":{"hn_show_points":1800,"github_stars_24h":"+3.1k"}},
    {"id":"n0603-08","rank":8,"category":"rising",
     "title":"GitHub Trending:MsEdge-WebUI-MCP — 让任意 Web 应用变成 MCP 工具",
     "source":"GitHub Trending","time":"2026-06-01 走红",
     "heat":{"score":2800,"level":"新星","sources":["github","hn"],
             "breakdown":"GitHub 24h +2.1k stars · HN ~640 points · 累计 9.4k stars"},
     "comments":134,
     "summary":"开源项目:把任何 Web 应用(包括 SaaS)的 UI 操作录制下来,自动转成 MCP 工具描述,让 Claude Code / Cursor 等 agent 直接调用——不需要等 SaaS 厂商开放 API。GitHub 单日涨 2.1k 星,Agent 工具链爆款。",
     "tags":["新应用","GitHub Trending","MCP","Agent 工具链"],
     "terms":["MCP","工具调用","Agent"],
     "rising_metrics":{"github_stars_24h":"+2.1k","total_stars":9400}},
    {"id":"n0603-09","rank":9,"category":"paper",
     "title":"arXiv:phi_first 单 Token 幻觉检测成为低成本基线标准",
     "source":"arXiv 2605.05166","time":"2026-06-02 引用激增",
     "heat":{"score":1700,"level":"中","sources":["paper","github"],
             "breakdown":"arXiv 持续高赞 · 24h 多次被新论文采用为 baseline"},
     "comments":56,
     "summary":'本周内 6 篇新论文主动把 phi_first 作为对比基线,标志"单 Token 置信度幻觉检测"正式成为低成本 SOTA 标准方法。',
     "tags":["幻觉检测","arxiv","基线"],
     "terms":["AUROC","归一化熵"]},
    {"id":"n0603-10","rank":10,"category":"paper",
     "title":"LongSeeker 论文配套代码成为 Agent 上下文管理参考实现",
     "source":"arXiv 2605.05191 · GitHub","time":"2026-06-02 累计 8.7k stars",
     "heat":{"score":1300,"level":"中","sources":["github","paper"],
             "breakdown":"GitHub 累计 +5.2k stars(本周)· 多家公司内部研究项目 fork"},
     "comments":42,
     "summary":"Context-ReAct 范式继续被广泛采用,GitHub Trending AI 工具分类周榜第二。多家 AI 公司内部 Agent 团队 fork 作为起点。",
     "tags":["Agent","上下文管理","GitHub"],
     "terms":["Context-ReAct","BrowseComp"]},
    {"id":"n0603-11","rank":11,"category":"industry",
     "title":"美国下调部分钢铝铜关税,AI 算力供应链成本压力暂缓",
     "source":"白宫公告 / 路透社","time":"2026-06-02",
     "heat":{"score":1900,"level":"中","sources":["media"],
             "breakdown":"白宫官方公告 · 主流财经媒体覆盖"},
     "comments":78,
     "summary":"特朗普依据《1962 年贸易扩展法》第 232 条款调整进口钢铝铜关税,收割机及部分农机从 25% 下调至 15%,本地成分门槛从 95% 降至 85%,缓解 AI 算力硬件供应链成本压力。",
     "tags":["关税","钢铝铜","AI 供应链"],
     "terms":["232 条款","AI 供应链"]},
    {"id":"n0603-12","rank":12,"category":"industry",
     "title":"宇树单款人形机器人累计下线 11000 台,H2+ 今年下半年上市",
     "source":"宇树官方 / 中新社","time":"2026-06-02",
     "heat":{"score":2400,"level":"中","sources":["media","x"],
             "breakdown":"具身智能圈 · ~3k X mentions"},
     "comments":98,
     "summary":"宇树单款双足人形(不含其他型号)截至 2026 年 5 月累计生产下线 11000 台。H2+ 将于今年下半年正式上市,搭载英伟达高性能算力平台。",
     "tags":["宇树","人形机器人","量产"],
     "terms":["H2+","GR00T"]},
    {"id":"n0603-13","rank":13,"category":"social",
     "title":"AI 岗位月薪 6 万,2026 年初新发岗位同比涨 12 倍",
     "source":"脉脉高聘人才智库","time":"2026-06-02 报告",
     "heat":{"score":1500,"level":"中","sources":["media","x"],
             "breakdown":"招聘行业报告 · 中文圈层广泛讨论"},
     "comments":145,
     "summary":'AI 岗位占新经济总岗位 26.23%(2025 同期 2.29%),供需比 0.97 接近供不应求,平均月薪 60738 元。最缺:Agent 开发 / RAG / 大模型辅助运维。',
     "tags":["AI 就业","人才市场","Agent"],
     "terms":["Agent","RAG"]},
    {"id":"n0603-14","rank":14,"category":"social",
     "title":"佛罗里达州起诉 OpenAI,要求标注高风险 AI 内容",
     "source":"财联社 / 凤凰网","time":"2026-06-02",
     "heat":{"score":2100,"level":"中","sources":["media","x"],
             "breakdown":"~3k X mentions · 中美法律圈关注"},
     "comments":167,
     "summary":'佛罗里达州成为美国首个对 OpenAI 提起诉讼的州政府,要求将 AI 生成内容标注为"高风险",需满足透明度、风险评估、人类监督、合规审查等要求。这可能推动其他州(加州、纽约、德州)跟随立法。',
     "tags":["AI 监管","OpenAI","美国州政府"],
     "terms":["OpenAI","AI 监管"]},
]

snap_0603 = {
    "date":"2026-06-03","weekday":"周三",
    "generated_at":"2026-06-03 08:00 (Asia/Shanghai)",
    "summary":"今天 AI 圈的核心叙事:微软 Build 重磅发布自研编程模型 MAI-Code-1-Flash,正式摆脱对 OpenAI 单一依赖;特朗普签署 AI 行政令,强能力模型公开发布前 30 天须通报;SpaceX 启动万亿级 IPO 进程。国产侧阿里 Qwen3.7-Plus 多模态、腾讯云 DeepSeek-V4 降价 97.5%、越疆 DobotWAM 具身大模型 99.25%——中美双线 + 资本 + 监管同步进入新阶段。",
    "stats":{"total_items":len(items_0603),"by_category":{}},
    "items":items_0603,
    "weekly_arc":{"label":"本周脉络","weeks":[]},
    "monthly_arc":{"label":"本月脉络","months":[]}
}
for it in items_0603:
    c=it["category"]
    snap_0603["stats"]["by_category"][c]=snap_0603["stats"]["by_category"].get(c,0)+1
with open(os.path.join(DATA,"archive","2026-06-03.json"),"w",encoding="utf-8") as f:
    json.dump(snap_0603,f,ensure_ascii=False,indent=2)
print(f"OK 2026-06-03 ({len(items_0603)} items)")

days=[]
for fn in sorted(os.listdir(os.path.join(DATA,"archive")), reverse=True):
    if not fn.endswith(".json") or fn=="index.json": continue
    fp=os.path.join(DATA,"archive",fn)
    with open(fp,"r",encoding="utf-8") as f:
        d=json.load(f)
    items=d.get("items",[])
    days.append({
        "date":d.get("date",fn[:-5]),
        "weekday":d.get("weekday",""),
        "summary":d.get("summary",""),
        "total":len(items),
        "rising":sum(1 for i in items if i.get("category")=="rising"),
        "headline":sum(1 for i in items if i.get("category")=="headline"),
    })
days.sort(key=lambda x:x["date"], reverse=True)
with open(os.path.join(DATA,"archive","index.json"),"w",encoding="utf-8") as f:
    json.dump({"days":days},f,ensure_ascii=False,indent=2)
print(f"OK index.json rebuilt, {len(days)} days total")
for d in days:
    print(f"  {d['date']} ({d['weekday']}) - {d['total']}条 / {d['rising']}新兴 / {d['headline']}头条")
